# Generated by Django 5.2 on 2025-04-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_live_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='kill_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='position_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
