# Generated by Django 5.2 on 2025-04-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_score_is_live_update_alter_score_bonus_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='rank',
        ),
    ]
